#:import PlotterScreen plottersim.screens.plotter_screen.PlotterScreen
#:import PlotterCanvas plottersim.widgets.plotter_canvas.PlotterCanvas
#:import Color kivy.graphics.Color

<PlotterScreen>:
    canvas:
        Color:
            rgba: (49.0/255.0, 47.0/255.0, 47.0/255.0, 1)
        Rectangle:
            pos: self.x, self.y
            size: self.width, self.height
    PlotterCanvas:
        id: plotter_canvas
        size: root.size
